CREATE TABLE playlists (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    owner INT NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (owner) REFERENCES users(id) ON DELETE CASCADE
) ENGINE = InnoDB;