// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"database/sql"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"open-music-go/controllers/album"
	controllers4 "open-music-go/controllers/playlist"
	controllers5 "open-music-go/controllers/playlist_collab"
	controllers2 "open-music-go/controllers/song"
	controllers3 "open-music-go/controllers/user"
	"open-music-go/repositories/album"
	repositories4 "open-music-go/repositories/playlist"
	repositories5 "open-music-go/repositories/playlist_activity"
	repositories6 "open-music-go/repositories/playlist_collab"
	repositories2 "open-music-go/repositories/song"
	repositories3 "open-music-go/repositories/user"
	"open-music-go/services/album"
	services3 "open-music-go/services/playlist"
	services4 "open-music-go/services/playlist_collab"
	services2 "open-music-go/services/song"
	"open-music-go/services/user"
)

// Injectors from wire.go:

func InitializeRouter() (*httprouter.Router, error) {
	albumRepositoryImpl := repositories.NewAlbumRepository()
	db := ProvideDB()
	validate := ProvideValidator()
	albumServiceImpl := services.NewAlbumService(albumRepositoryImpl, db, validate)
	albumControllerImpl := controllers.NewAlbumController(albumServiceImpl)
	songRepositoryImpl := repositories2.NewSongRepository()
	songServiceImpl := services2.NewSongService(songRepositoryImpl, db, validate)
	songControllerImpl := controllers2.NewSongController(songServiceImpl)
	userRepositoryImpl := repositories3.NewUserRepository()
	userServiceImpl := service.NewUserService(userRepositoryImpl, db, validate)
	userControllerImpl := controllers3.NewUserController(userServiceImpl)
	playlistRepositoryImpl := repositories4.NewPlaylistRepository()
	playlistActivityRepositoryImpl := repositories5.NewPlaylistActivityRepository()
	playlistServiceImpl := services3.NewPlaylistService(playlistRepositoryImpl, songRepositoryImpl, playlistActivityRepositoryImpl, db, validate)
	playlistControllerImpl := controllers4.NewPlaylistController(playlistServiceImpl)
	playlistCollabRepositoryImpl := repositories6.NewPlaylistCollabRepository()
	playlistCollabServiceImpl := services4.NewPlaylistCollabService(playlistCollabRepositoryImpl, playlistRepositoryImpl, userRepositoryImpl, db, validate)
	playlistCollabControllerImpl := controllers5.NewPlaylistCollabController(playlistCollabServiceImpl)
	router := NewRouter(albumControllerImpl, songControllerImpl, userControllerImpl, playlistControllerImpl, playlistCollabControllerImpl)
	return router, nil
}

// wire.go:

func ProvideDB() *sql.DB {
	return NewDB()
}

func ProvideValidator() *validator.Validate {
	return validator.New()
}

var repoSet = wire.NewSet(repositories.NewAlbumRepository, wire.Bind(new(repositories.AlbumRepository), new(*repositories.AlbumRepositoryImpl)), repositories2.NewSongRepository, wire.Bind(new(repositories2.SongRepository), new(*repositories2.SongRepositoryImpl)), repositories3.NewUserRepository, wire.Bind(new(repositories3.UserRepository), new(*repositories3.UserRepositoryImpl)), repositories4.NewPlaylistRepository, wire.Bind(new(repositories4.PlaylistRepository), new(*repositories4.PlaylistRepositoryImpl)), repositories6.NewPlaylistCollabRepository, wire.Bind(new(repositories6.PlaylistCollabRepository), new(*repositories6.PlaylistCollabRepositoryImpl)), repositories5.NewPlaylistActivityRepository, wire.Bind(new(repositories5.PlaylistActivityRepository), new(*repositories5.PlaylistActivityRepositoryImpl)))

var serviceSet = wire.NewSet(services.NewAlbumService, wire.Bind(new(services.AlbumService), new(*services.AlbumServiceImpl)), services2.NewSongService, wire.Bind(new(services2.SongService), new(*services2.SongServiceImpl)), service.NewUserService, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)), services3.NewPlaylistService, wire.Bind(new(services3.PlaylistService), new(*services3.PlaylistServiceImpl)), services4.NewPlaylistCollabService, wire.Bind(new(services4.PlaylistCollabService), new(*services4.PlaylistCollabServiceImpl)))

var controllerSet = wire.NewSet(controllers.NewAlbumController, wire.Bind(new(controllers.AlbumController), new(*controllers.AlbumControllerImpl)), controllers2.NewSongController, wire.Bind(new(controllers2.SongController), new(*controllers2.SongControllerImpl)), controllers3.NewUserController, wire.Bind(new(controllers3.UserController), new(*controllers3.UserControllerImpl)), controllers4.NewPlaylistController, wire.Bind(new(controllers4.PlaylistController), new(*controllers4.PlaylistControllerImpl)), controllers5.NewPlaylistCollabController, wire.Bind(new(controllers5.PlaylistCollabController), new(*controllers5.PlaylistCollabControllerImpl)))
